language: node_js
node_js:
- node
before_install: npm install -g grunt-cli && npm install -g bower
install: npm install
before_script: grunt prod
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - echo "Deploying cs2-ui-library to gh-pages..."
  - cd build
  - git init
  - git add .
  - git commit -m "Auto deploy to GitHub pages from Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/thezimmee/cs2-ui-library" master:gh-pages
after_success:
  - echo "[OK] Deployed to GitHub pages!"
notifications:
  email:
    recipients:
    - thezimmee@gmail.com
    on_success: always
    on_failure: always
