language: node_js
node_js:
  - "node"
before_install: npm install -g grunt-cli && npm install -g bower
install: npm install
before_script: grunt prod
script: grunt deploy --nobuild
notifications:
  email:
    recipients:
      - thezimmee@gmail.com
    on_success: always
    on_failure: always
