language: node_js
node_js:
- node
before_install: npm install -g grunt-cli && npm install -g bower
install: npm install
before_script: grunt prod
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - echo "Deploying cs2-ui-library to gh-pages..."
  - cd build
  - git init
  - git add .
  - git commit -m "Auto deploy to GitHub pages from Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/thezimmee/cs2-ui-library" master:gh-pages > /dev/null 2>$1
after_success:
  - echo "[OK] Deployed to GitHub pages!"
notifications:
  email:
    recipients:
    - thezimmee@gmail.com
    on_success: always
    on_failure: always
env:
  global:
    secure: jVKrnaGWWwWos6kKWSuukW4Snl/+k5SOPLdFjp0Ut0odazQpGdLXIffJOtgIh9Mrz6B/7HKjN4xMfm9rP01epskBqYTo0//thtlEbwhaaYu6q22UV2kHzEOv3WitK1OvSlRCGxHcK4pAfsRdx8n7+S54ahIHM1VPR4D1mClO5GcZ3qsu7H1dJvGqjLsP3C+Del5Ufjuy5MxssFzr/dUoVePAgvjm48RHIOr1YpMAZkqZMzV6RG9fA85RUbmTQUKIY4IBcq8p0ubOLzhEkULkUezISczC+d+grR+H9fLRuRkdXTqzf/4R1+Uij3z3hnrCqmgsg1puSWddtY7ZtVDjGv2bJ9KuUUZTIdrCVcdrv6+srHAw/BUI7MDehsZ75S11B2cVZ1k7f5T4wXz5dRlCDemJAUAU3aygUj1Ymu47JXNDeaVSb17VYTI4xnIMLhUt6m7hb6130jlDHH4j2OsdV0TIQuFtaynn0Zidc7eoHDsO+FIUU/amyp52Q6ZATb/I5Aa71bpJdDu1N7edxH8gvmcnl3pGpYLP9+dAQV0Ph6+1pg/IB029VCfAe0nEm2gpQJ/F84HeGjxPuSdHfqoEp38ydQlJW79zF4uS+54Asfg0TSpQsHhJqeQRKDaM5PGGqowrIKm9/qxOg3SENmgUBun3hhUJAFlxpvWWw9LOcxU=
